import logging

from fastapi import FastAPI, HTTPException, Request, status
from pydantic import BaseModel
from app.config import ENVIRONMENT, LOG_LEVEL


# Configure application logging.
logging.basicConfig(
    level=LOG_LEVEL,
    format="%(asctime)s  %(levelname)s  %(message)s",
    datefmt="%Y-%m-%d %H:%M:%S",
)

logger = logging.getLogger(__name__)


# Main FastAPI application instance.
# All API endpoints are registered on this object.
app = FastAPI()


@app.middleware("http")
async def log_requests(request: Request, call_next):
    """
    Log every HTTP request processed by the application.

    Successful responses are logged as INFO.
    Client errors are logged as WARNING.
    Server errors are logged as ERROR.
    """

    try:
        response = await call_next(request)

    except Exception:
        logger.exception(
            "%s %s 500",
            request.method,
            request.url.path,
        )
        raise

    if response.status_code >= 500:
        log = logger.error
    elif response.status_code >= 400:
        log = logger.warning
    else:
        log = logger.info

    log(
        "%s %s %s",
        request.method,
        request.url.path,
        response.status_code,
    )

    return response

class TaskCreate(BaseModel):
    """
    Data expected from the client when creating a new task.

    The client does not provide an ID because it is generated
    automatically by the application.
    """

    # Description of the task.
    title: str

    # Indicates whether the task has been completed.
    # New tasks are incomplete by default.
    completed: bool = False


class Task(BaseModel):
    """
    Complete representation of a task returned by the API.
    """

    # Unique identifier generated by the application.
    id: int

    # Description of the task.
    title: str

    # Current completion status of the task.
    completed: bool

# Temporary task storage.
#
# Tasks are stored only in RAM, so all data will be lost whenever
# the application is stopped or restarted.
#
# A persistent database will be introduced in a later phase.
tasks: list[Task] = []


# Identifier that will be assigned to the next created task.
next_id = 1


# Root endpoint

@app.get("/")
def root():
    """
    Return basic message
    """

    return {
        "message": "Cloud Native DevSecOps API"
    }


# GET /tasks

@app.get(
    "/tasks",
    response_model=list[Task],
)
def get_tasks():
    """
    Return all tasks currently stored in memory.

    HTTP response:
        200 OK
    """

    return tasks


# GET /tasks/{task_id}

@app.get(
    "/tasks/{task_id}",
    response_model=Task,
)
def get_task(task_id: int):
    """
    Return a single task identified by its ID.

    HTTP responses:
        200 OK        -> Task exists.
        404 Not Found -> Task does not exist.
    """

    # Search the in-memory task list for the requested ID.
    for task in tasks:
        if task.id == task_id:
            return task

    # If the loop finishes without finding the task,
    # return an HTTP 404 response.
    raise HTTPException(
        status_code=status.HTTP_404_NOT_FOUND,
        detail="Task not found",
    )


# POST /tasks

@app.post(
    "/tasks",
    response_model=Task,
    status_code=status.HTTP_201_CREATED,
)
def create_task(task_data: TaskCreate):
    """
    Create a new task.

    HTTP responses:
        201 Created              -> Task successfully created.
        422 Unprocessable Entity -> Request body validation failed (Pydantic).
    """

    # We modify the global next_id variable after creating each task.
    global next_id

    # Create the complete Task object.
    #
    # The title and completed fields come from validated client data,
    # while the ID is generated by the application.
    task = Task(
        id=next_id,
        title=task_data.title,
        completed=task_data.completed,
    )

    # Store the task in memory.
    tasks.append(task)

    # Prepare the identifier for the next task.
    next_id += 1

    # Return the newly created task.
    return task


# DELETE /tasks/{task_id}

@app.delete(
    "/tasks/{task_id}",
    status_code=status.HTTP_204_NO_CONTENT,
)
def delete_task(task_id: int):
    """
    Delete a task identified by its ID.

    HTTP responses:
        204 No Content -> Task successfully deleted.
        404 Not Found  -> Task does not exist.
    """

    # enumerate() provides both:
    #
    #   index -> position of the task inside the list
    #   task  -> Task object stored at that position
    for index, task in enumerate(tasks):
        if task.id == task_id:

            # Remove the matching task from memory.
            tasks.pop(index)

            # HTTP 204 responses must not contain a response body.
            return

    # If no task matches the requested ID, return HTTP 404.
    raise HTTPException(
        status_code=status.HTTP_404_NOT_FOUND,
        detail="Task not found",
    )


@app.get("/health")
def health():
    """
    Indicate whether the application process is alive.

    This endpoint is intended for liveness checks.

    HTTP response:
        200 OK -> Application process is running.
    """

    return {
        "status": "ok"
    }


@app.get("/ready")
def ready():
    """
    Indicate whether the application is ready to receive traffic.

    At this stage, the application has no external dependencies,
    so readiness is always reported as successful.

    In future phases, this endpoint may check dependencies such as
    databases or external services.

    HTTP response:
        200 OK -> Application is ready to receive traffic.
    """

    return {
        "status": "ok"
    }